spring:
  application:
    name: Spring Boot Blueprint
  autoconfigure: # prevents spring from showing default user password in logs on startup
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  groovy:
    template:
      check-template-location: false
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      max-lifetime: 2000000
      connectionTimeout: 30000
      idle-timeout: 30000
  sql:
    init:
      platform: postgres
      enabled: true
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # (create, create-drop, validate, update)
    open-in-view: false
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true

logging:
  config: classpath:config/logging/logback-spring.xml

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus
